- name: Create OpenShift Virtualization VM snapshot
  hosts: localhost
  #hosts: openshift
  connection: local
  gather_facts: false

  vars:
    # VM details
    #vm_name: my-test-vm
    #vm_project: default
    #snapshot_name: snap1

    # API access
    #api_key: "{{ lookup('env', 'OPENSHIFT_API_KEY') }}"
    validate_certs: false

  tasks:
  - name: Create snapshot
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: snapshot.kubevirt.io/v1beta1
        kind: VirtualMachineSnapshot
        metadata:
          finalizers:
          - snapshot.kubevirt.io/vmsnapshot-protection
          generation: 1
          name: "{{ snapshot_name }}"
          namespace: "{{ vm_project }}"
        spec:
          source:
            apiGroup: kubevirt.io
            kind: VirtualMachine
            name: "{{ vm_name }}"

  - name: Expose EniCloud snapshot create result
    ansible.builtin.set_stats:
      data:
        resource_id: "{{ snapshot_name }}"
        snapshot_id: "{{ snapshot_name }}"
        snapshot_name: "{{ snapshot_name }}"
        vm_name: "{{ vm_name }}"
        vm_project: "{{ vm_project }}"
        namespace: "{{ vm_project }}"
        status: created
        eni_result:
          resource_id: "{{ snapshot_name }}"
          snapshot_id: "{{ snapshot_name }}"
          snapshot_name: "{{ snapshot_name }}"
          vm_resource_id: "{{ vm_name }}"
          vm_name: "{{ vm_name }}"
          vm_project: "{{ vm_project }}"
          namespace: "{{ vm_project }}"
          status: created
