- name: List VMS on OpenShift Virtualization
  #hosts: localhost
  hosts: openshift
  #connection: local
  gather_facts: false
  vars:
    vm_project: default

  tasks:
  - name: Get a list of all VirtualMachines
    redhat.openshift_virtualization.kubevirt_vmi_info:
      api_key: "{{ api_key }}"
    register: output

  - name: return list of all VirtualMachines
    #debug:
    #  #msg: "{{item}}"
    #  msg: "{{item.metadata.name }} {{item.spec.domain.cpu.cores }} {{item.spec.domain.memory.guest }} {{ item.status.interfaces[0].ipAddress }} {{item.status.phase }}"
    #loop: "{{ output.resources }}"

    set_fact:
      final_vm_list: "{{ final_vm_list | default([]) + [item_data] }}"
    vars:
      item_data:
        name: "{{ item.metadata.name  }}"
        vcpu: "{{ item.spec.domain.cpu.cores }}"
        memory: "{{ item.spec.domain.memory.guest }}"
        ipAddress: "{{ item.status.interfaces[0].ipAddress }}"
        phase: "{{ item.status.phase }}"
    loop: "{{ output.resources }}"

  - name: return list of all VirtualMachines
    debug:
      var: final_vm_list